//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMTI_Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Artist
    {
        public int ArtistId { get; set; }

        [Display(Name="Artist Name")]
        [Required(ErrorMessage="This field cannot be empty")]
        public string ArtistName { get; set; }

        [Display(Name = "Package Name")]
        [Required(ErrorMessage = "This field cannot be empty")]
        public string PackageName { get; set; }

        [Display(Name = "Image")]
        public string ImageUrl { get; set; }

        [Display(Name = "Release Date")]
        [Required(ErrorMessage = "This field cannot be empty")]
        public System.DateTime ReleaseDate { get; set; }

        [Required(ErrorMessage = "This field cannot be empty")]
        [Range(1,9999999999,ErrorMessage="Must be number")]
        public decimal Price { get; set; }

        [Display(Name = "Sample Music")]
        public string SampleUrl { get; set; }
    }
}
